### ISSUE TITLE
Error while running npm run dev at webpack.js

### ISSUE THREAD

**Issue by ubakarasamy** [bradtraversy/lsapp#4]
Hello,
Thanks for the great tutorial,

I'm getting this error while running npm run dev

>  ERROR  Failed to compile with 2 errors                                                                                                 13:34:39
> 
>  error  in ./resources/assets/sass/app.scss
> 
> Module build failed: Error: ENOENT: no such file or directory, scandir '/var/www/lsapp/node_modules/node-sass/vendor'
>     at Object.fs.readdirSync (fs.js:924:18)
>     at Object.getInstalledBinaries (/var/www/lsapp/node_modules/node-sass/lib/extensions.js:128:13)
>     at foundBinariesList (/var/www/lsapp/node_modules/node-sass/lib/errors.js:20:15)
>     at foundBinaries (/var/www/lsapp/node_modules/node-sass/lib/errors.js:15:5)
>     at Object.module.exports.missingBinary (/var/www/lsapp/node_modules/node-sass/lib/errors.js:45:5)
>     at module.exports (/var/www/lsapp/node_modules/node-sass/lib/binding.js:15:30)
>     at Object.<anonymous> (/var/www/lsapp/node_modules/node-sass/lib/index.js:14:35)
>     at Module._compile (module.js:641:30)
>     at Object.Module._extensions..js (module.js:652:10)
>     at Module.load (module.js:560:32)
>     at tryModuleLoad (module.js:503:12)
>     at Function.Module._load (module.js:495:3)
>     at Module.require (module.js:585:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/var/www/lsapp/node_modules/sass-loader/lib/loader.js:3:14)
>     at Module._compile (module.js:641:30)
>     at Object.Module._extensions..js (module.js:652:10)
>     at Module.load (module.js:560:32)
>     at tryModuleLoad (module.js:503:12)
>     at Function.Module._load (module.js:495:3)
>     at Module.require (module.js:585:17)
>     at require (internal/module.js:11:18)
>     at loadLoader (/var/www/lsapp/node_modules/loader-runner/lib/loadLoader.js:13:17)
>     at iteratePitchingLoaders (/var/www/lsapp/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
>     at iteratePitchingLoaders (/var/www/lsapp/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
>     at /var/www/lsapp/node_modules/loader-runner/lib/LoaderRunner.js:173:18
>     at loadLoader (/var/www/lsapp/node_modules/loader-runner/lib/loadLoader.js:36:3)
>     at iteratePitchingLoaders (/var/www/lsapp/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
>     at iteratePitchingLoaders (/var/www/lsapp/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
>     at /var/www/lsapp/node_modules/loader-runner/lib/LoaderRunner.js:173:18
> 
>  @ ./resources/assets/sass/app.scss 4:14-266
>  @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss
> 
And my log files are
[2018-02-02T08_04_39_582Z-debug.log](https://github.com/bradtraversy/lsapp/files/1688558/2018-02-02T08_04_39_582Z-debug.log)
[2018-02-02T08_04_39_636Z-debug.log](https://github.com/bradtraversy/lsapp/files/1688559/2018-02-02T08_04_39_636Z-debug.log)

**Comment by mzubairhassan** [comment]
I think you are missing steps to compile assets and sass files in public folder. Try checking package.json file and make sure there is bootstrap and then do 
npm install 
and  then
npm run dev

**Comment by mzubairhassan** [comment]
"devDependencies": {
        "axios": "^0.17",
        "bootstrap-sass": "^3.3.7",
        "cross-env": "^5.1",
        "jquery": "^3.2",
        "laravel-mix": "^1.0",
        "lodash": "^4.17.4",
        "vue": "^2.5.7"
    }

**Comment by mzubairhassan** [comment]
check here if package.json in root directory contains these then run npm install again
    "devDependencies": {
        "axios": "^0.17",
        **"bootstrap-sass": "^3.3.7",**
        "cross-env": "^5.1",
        "jquery": "^3.2",
        "laravel-mix": "^1.0",
        "lodash": "^4.17.4",
        "vue": "^2.5.7"
    }
