### ISSUE TITLE
vendor file does not exist 

### ISSUE THREAD

**Issue by mohammedilamine** [bradtraversy/lsapp#8]
it does not work for me I think the problem is that the vendor file does not exist 
but when I copy it in the project folder this error in the browser show up :
"Class 'Collective\Html\HtmlServiceProvider' not found"
in : C:\xampp\htdocs\lsapp-master\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php

**Comment by cbolboros** [comment]
After you download the project to the Xampp/Htdocs folder, just do a `composer update` in that project folder and it will reinstall the dependencies.

**Comment by mohammedilamine** [comment]
it worked thanks
