### ISSUE TITLE
authentication error

### ISSUE THREAD

**Issue by jeraudah** [bradtraversy/lsapp#9]
please help cant seem to by pass this error

SQLSTATE[HY000]: General error: 1364 Field 'user_id' doesn't have a default value (SQL: insert into `posts` (`title`, `body`, `updated_at`, `created_at`) values (post four, <p>this is post four</p>, 2018-04-12 12:56:57, 2018-04-12 12:56:57))

WHAT am i missing?

**Comment by Lanatel** [comment]
You want to insert a new record to table but you  didn't define a value for user_id column, so you got this error cause it doesn't have a default value. (for example you can do smth like that **$post->user_id = auth()->id()** ). And plus add a '**user_id**' value to fillable array in your post model

**Comment by jeraudah** [comment]
thanks
